version: "3"
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.2.3
    env_file:
      - terraform/.env
    volumes:
      -  ./terraform:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true